dbt_basket_craft:
  outputs:
    dev:
      dbname: basket_craft
      host: isba-dev-02.cybuu46o4wt7.us-east-1.rds.amazonaws.com
      pass: isba_4715
      port: 5432
      schema: dev
      threads: 1
      type: postgres
      user: postgres
    prod:
      dbname: basket_craft
      host: isba-dev-02.cybuu46o4wt7.us-east-1.rds.amazonaws.com
      pass: isba_4715
      port: 5432
      schema: staging
      threads: 1
      type: postgres
      user: postgres
    target: dev
